front:
  replicas: 1
  image: nafrin/python-frontend
  version: "{{ .Values.front.version }}"
  port: 5000
  targetPort: 5000
  backendUrl: "http://back:5001"

back:
  replicas: 1
  image: nafrin/python-backend
  version: "{{ .Values.back.version }}"
  port: 5001
  targetPort: 5001
  mongoUrl: "mongodb://mongo:27017"

mongo:
  replicas: 1
  image: nafrin/python-mongodb
  version: "{{ .Values.mongo.version }}"
  port: 27017
  targetPort: 27017 
