version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    depends_on:
      - api